// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Santuario.Negocio.Context;

#nullable disable

namespace Santuario.Negocio.Migrations
{
    [DbContext(typeof(SantuarioDbContext))]
    [Migration("20260221144223_InitialSantuario")]
    partial class InitialSantuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Santuario.Entidade.Entities.CarrosselItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataalteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuarioalteracao");

                    b.Property<int?>("IdUsuarioCriacao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuariocriacao");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagemurl");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("carrossel_item", (string)null);
                });

            modelBuilder.Entity("Santuario.Entidade.Entities.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("categoria");

                    b.Property<string>("ConteudoHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudohtml");

                    b.Property<string>("ConteudoJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conteudojson");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataalteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datapublicacao");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuarioalteracao");

                    b.Property<int?>("IdUsuarioCriacao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuariocriacao");

                    b.Property<string>("ImagemCapaUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagemcapaurl");

                    b.Property<bool>("PermiteComentarios")
                        .HasColumnType("boolean")
                        .HasColumnName("permitecomentarios");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("resumo");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subcategoria")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("subcategoria");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_noticia_slug");

                    b.ToTable("noticia", (string)null);
                });

            modelBuilder.Entity("Santuario.Entidade.Entities.NoticiaComentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataalteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<int>("IdNoticia")
                        .HasColumnType("integer")
                        .HasColumnName("idnoticia");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuarioalteracao");

                    b.Property<int?>("IdUsuarioCriacao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuariocriacao");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("usuarioemail");

                    b.Property<string>("UsuarioNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuarionome");

                    b.Property<string>("UsuarioProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuarioprovider");

                    b.Property<string>("UsuarioProviderId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("usuarioproviderid");

                    b.HasKey("Id");

                    b.HasIndex("IdNoticia", "Ativo")
                        .HasDatabaseName("ix_noticia_comentario_noticia_ativo");

                    b.ToTable("noticia_comentario", (string)null);
                });

            modelBuilder.Entity("Santuario.Entidade.Entities.Sobre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataalteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<string>("Descricao1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao1");

                    b.Property<string>("Descricao2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao2");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuarioalteracao");

                    b.Property<int?>("IdUsuarioCriacao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuariocriacao");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagemurl");

                    b.Property<string>("Titulo1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo1");

                    b.Property<string>("Titulo2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo2");

                    b.HasKey("Id");

                    b.ToTable("sobre", (string)null);
                });

            modelBuilder.Entity("Santuario.Entidade.Entities.SobreTopico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dataalteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<int>("IdSobre")
                        .HasColumnType("integer")
                        .HasColumnName("idsobre");

                    b.Property<int?>("IdUsuarioAlteracao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuarioalteracao");

                    b.Property<int?>("IdUsuarioCriacao")
                        .HasColumnType("integer")
                        .HasColumnName("idusuariocriacao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id");

                    b.HasIndex("IdSobre");

                    b.ToTable("sobre_topico", (string)null);
                });

            modelBuilder.Entity("Santuario.Entidade.Entities.NoticiaComentario", b =>
                {
                    b.HasOne("Santuario.Entidade.Entities.Noticia", "Noticia")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdNoticia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noticia");
                });

            modelBuilder.Entity("Santuario.Entidade.Entities.SobreTopico", b =>
                {
                    b.HasOne("Santuario.Entidade.Entities.Sobre", "Sobre")
                        .WithMany("Topicos")
                        .HasForeignKey("IdSobre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sobre");
                });

            modelBuilder.Entity("Santuario.Entidade.Entities.Noticia", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("Santuario.Entidade.Entities.Sobre", b =>
                {
                    b.Navigation("Topicos");
                });
#pragma warning restore 612, 618
        }
    }
}
